export const SET_USERS = "SET_USERS",
  SET_USER_DETAILS = "SET_USER_DETAILS",
  UPDATE_ACTIVE_USER = "UPDATE_ACTIVE_USER",
  RESET_ACTIVE_USER = "RESET_ACTIVE_USER",
  SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
